---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "database-config"
  labels:
    app.kubernetes.io/name: "aspire"
    app.kubernetes.io/component: "Database"
    app.kubernetes.io/instance: "{{.Release.Name}}"
data:
  POSTGRES_HOST_AUTH_METHOD: "{{ .Values.config.Database.POSTGRES_HOST_AUTH_METHOD }}"
  POSTGRES_INITDB_ARGS: "{{ .Values.config.Database.POSTGRES_INITDB_ARGS }}"
