---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "api-deployment"
  labels:
    app.kubernetes.io/name: "aspire"
    app.kubernetes.io/component: "Api"
    app.kubernetes.io/instance: "{{.Release.Name}}"
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "aspire"
        app.kubernetes.io/component: "Api"
        app.kubernetes.io/instance: "{{.Release.Name}}"
    spec:
      containers:
        - image: "{{ .Values.parameters.Api.Api_image }}"
          name: "Api"
          envFrom:
            - configMapRef:
                name: "api-config"
            - secretRef:
                name: "api-secrets"
          ports:
            - name: "http"
              protocol: "TCP"
              containerPort: "{{ .Values.parameters.Api.port_http }}"
            - name: "https"
              protocol: "TCP"
              containerPort: "{{ .Values.parameters.Api.port_https }}"
          imagePullPolicy: "IfNotPresent"
  selector:
    matchLabels:
      app.kubernetes.io/name: "aspire"
      app.kubernetes.io/component: "Api"
      app.kubernetes.io/instance: "{{.Release.Name}}"
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: "RollingUpdate"
