---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "web-service"
  labels:
    app.kubernetes.io/name: "aspire"
    app.kubernetes.io/component: "Web"
    app.kubernetes.io/instance: "{{.Release.Name}}"
spec:
  type: "ClusterIP"
  selector:
    app.kubernetes.io/name: "aspire"
    app.kubernetes.io/component: "Web"
    app.kubernetes.io/instance: "{{.Release.Name}}"
  ports:
    - name: "http"
      protocol: "TCP"
      port: "{{ .Values.parameters.Web.port_http }}"
      targetPort: "{{ .Values.parameters.Web.port_http }}"
    - name: "https"
      protocol: "TCP"
      port: "{{ .Values.parameters.Web.port_https }}"
      targetPort: "{{ .Values.parameters.Web.port_https }}"
